DECLARE @ITEM_ID nvarchar(50)  
DECLARE ITEM_CURSOR CURSOR  
FOR
SELECT TOP 5 itemCode 
FROM OITM
WHERE U_SyncSAP = 'Y'

OPEN ITEM_CURSOR 
FETCH NEXT FROM ITEM_CURSOR INTO @ITEM_ID -- We fetch the first result
 
WHILE @@FETCH_STATUS = 0 --If the fetch went well then we go for it
BEGIN
 
	EXEC se_DIES_Code '4' , 'A' ,  1, 'ItemCode', @item_id, 'OITM_TO_BTF_OITM' 
	FETCH NEXT FROM ITEM_CURSOR INTO @ITEM_ID 

END

CLOSE ITEM_CURSOR  
DEALLOCATE ITEM_CURSOR 